image: gitpod/workspace-cpp

tasks:
  - name: Setup BitTorrent Client
    init: |
      sudo apt-get update
      sudo apt-get install -y libboost-all-dev libssl-dev cmake build-essential
      chmod +x run.sh build.sh
    command: |
      echo "🚀 BitTorrent Client Ready!"
      echo ""
      echo "Two simple commands:"
      echo "  ./run.sh docker    # 🐳 Instant demo"
      echo "  ./run.sh build     # 🔧 Local build"
      echo ""

ports:
  - port: 6881
    onOpen: notify
    description: BitTorrent Client Port

vscode:
  extensions:
    - ms-vscode.cpptools
    - ms-vscode.cmake-tools
    - ms-azuretools.vscode-docker 